"""crear tabla user_2fa_settins

Revision ID: afa5aefd7080
Revises: 9d2213b7e9e7
Create Date: 2025-05-12 18:59:00.354274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa5aefd7080'
down_revision: Union[str, None] = '9d2213b7e9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_2fa_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_totp_secret', sa.LargeBinary(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_backup_codes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_2fa_settings_id'), 'user_2fa_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_2fa_settings_user_id'), 'user_2fa_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_2fa_settings_user_id'), table_name='user_2fa_settings')
    op.drop_index(op.f('ix_user_2fa_settings_id'), table_name='user_2fa_settings')
    op.drop_table('user_2fa_settings')
    # ### end Alembic commands ###
